disabled_rules:
  - control_statement
  - empty_count
  - file_header
  - unused_optional_binding
  - identifier_name
  - let_var_whitespace
  - nesting
included:
  - BASwiftExample
excluded:
  - Pods
opt_in_rules:
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  Burak Akkaya
                    \/\/
                    \/\/
identifier_name:
  excluded:
    - id
line_length: 149
number_separator:
  minimum_length: 5