# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!


target 'BASwiftExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BASwiftExample
  pod 'BASwift', :path => "../"
  pod 'BASwift/SDWebImage', :path => "../"
  pod 'BASwift/Alamofire', :path => "../"
  pod 'BASwift/Realm', :path => "../"
  #pod 'BASwift', :git => 'https://github.com/brkakkaya/baswift.git'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'SwiftLint'

  target 'BASwiftExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
